[package]
name = "drahtbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
clap = { version = "4.0", features = ["derive"] }
octocrab = { version = "0.17", features = ["stream"] }
thiserror = "1.0"
serde_json = "1.0"
async-trait = "0.1"
futures-util = "0.3"
lazy_static = "1.4"